php:
    - 5.5

before_script:
  - cp app/config/parameters.yml.travis app/config/parameters.yml
  - composer install  -o
  - php app/console doctrine:database:create --env=test
  - php app/console doctrine:schema:create --env=test
