uifi_grup_lac_scraper:
    resource: "@UIFIGrupLACScraperBundle/Controller/"
    type:     annotation
    prefix:   /

uifi_integrantes:
    resource: "@UIFIIntegrantesBundle/Controller/"
    type:     annotation
    prefix:   /

users:
    resource: "@UsersBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: @AppBundle/Controller/
    type:     annotation

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"


admin:
    resource: '@SonataAdminBundle/Resources/config/routing/sonata_admin.xml'
    prefix: /admin

_sonata_admin:
    resource: .
    type: sonata_admin
    prefix: /admin

    
