security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_INTEGRANTE:  [ROLE_INTEGRANTE]
        ROLE_DIRECTOR:    [ROLE_DIRECTOR]
        ROLE_ADMIN:       [ROLE_USER, ROLE_PROVIDER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_PROVIDER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]


    providers:
        user:
            entity: { class: UsersBundle\Entity\Usuario, property: email}

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: user
                csrf_provider: form.csrf_provider
                success_handler: users.handler.login_success_handler
            anonymous:    true


    access_control:
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }
        - { path: ^/integrantes/, role: ROLE_INTEGRANTE }
        - { path: ^/director/, role: ROLE_DIRECTOR }
