# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    app.corsListener:
        class: AppBundle\EventListener\CorsListener
        tags:
          - { name: kernel.evnet_listener, event: kernel.response, method: onKernelResponse }
