<?php

namespace UIFI\ProductosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends EntityRepository
{
  /**
   * Funcion que se encarga de eliminar todos los registros
   * de la entidad
  */
  public function deleteAll(){
    $em = $this->getEntityManager();
    return $em->createQuery('DELETE FROM UIFIProductosBundle:Articulo')->execute();
  }

  /**
  * Cuenta el número de articulos publicados por año en la facultad
  *
  */
  public function getCountByYear(){
    $em = $this->getEntityManager();
    $connection = $em->getConnection();
    $sql = 'SELECT COUNT(a.anual) AS cantidad, a.anual AS fecha FROM  articulo a
            GROUP BY a.anual';
    $em = $this->getEntityManager();
    $statement = $connection->prepare($sql);
    $statement->execute();
    $results = $statement->fetchAll();
    return $results;
  }
}
