<?php

namespace UIFI\ProductosBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ArticuloRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticuloRepository extends EntityRepository
{
  /**
   * Funcion que se encarga de eliminar todos los registros
   * de la entidad
  */
  public function deleteAll(){
    $em = $this->getEntityManager();
    return $em->createQuery('DELETE FROM UIFIProductosBundle:Articulo')->execute();
  }
}
