<?php

namespace UIFI\IntegrantesBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * GrupoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class GrupoRepository extends EntityRepository
{
  /**
   * Función que se encarga de eliminar todos los registros
   * de la entidad
  */
  public function deleteAll(){
    $em = $this->getEntityManager();
    return $em->createQuery('DELETE FROM UIFIIntegrantesBundle:Grupo')->execute();
  }

  /**
   * Función que se encarga de contar el número de artículos que tiene publicado
   * un grupo de investigación de acuerdo de las publicaciones realizadas por
   * cada uno de los integrantes del grupo de Investigación.
   *
   * @FIXME: ¿Que ocurre si  un artículo tiene varios autores en el mismo grupo?
   *
   * @param $code Id del grupo de investigación.
   * @return Integer con la cuenta de artículos por grupo.
   *
  */
  public function getCountArticulosByGrupo( $code ){
    $em = $this->getEntityManager();
    $connection = $em->getConnection();
    $sql = "SELECT count(DISTINCT a.id) as cantidad
      FROM  grupo g, integrante i,grupo_integrante gi, articulo a,integrantes_articulos ia
      WHERE g.id = :code AND gi.grupo_id = g.id AND gi.integrante_id = i.id AND a.grupo = g.id
        AND ia.integrante_id = i.id AND ia.articulo_id  = a.id";

    $statement = $connection->prepare($sql);
    $statement->bindValue('code', $code);
    $statement->execute();
    $results = $statement->fetchAll();
    if( count($results)>0){
        $value = $results[0];
        $value = intval($value['cantidad']);
        return $value;
    }
    return 0;
  }

  /**
   * Función que se encarge de contar el número de artículos que tiene publicado
   * un grupo de investigación de acuerdo a las publicaciones realizadas por los
   * integrantes , discriminado por año.
   *
   * @param $code Código del grupo de investigación.
   * @return Integer con la cuenta de artículos por grupo.
  */
  public function getCountArticulosByYear($code){
    $em = $this->getEntityManager();
    $connection = $em->getConnection();
    $sql = 'SELECT  COUNT(DISTINCT (a.id)) as cantidad, g.nombre, a.anual
          FROM  articulo a, integrantes_articulos  ia, integrante i,
            grupo g, grupo_integrante gi
          WHERE  g.id = :code  AND ia.articulo_id = a.id AND ia.integrante_id = i.id
            AND gi.grupo_id = g.id AND gi.integrante_id = i.id
          GROUP BY g.id,a.anual ORDER BY a.anual,g.nombre';
    $statement = $connection->prepare($sql);
    $statement->bindValue('code', $code);
    $statement->execute();
    $results = $statement->fetchAll();
    return $results;
  }
}
