<?php

namespace UIFI\IntegrantesBundle\Repository;

use Doctrine\ORM\EntityRepository;
use UIFI\IntegrantesBundle\Entity\Integrante;

/**
 * IntegranteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 *
 * @author Cristian Camilo Chaparro <cristianchaparroa@gmail.com>
 */
class IntegranteDirectorRepository extends EntityRepository
{

  /**
   * Funcion que se encarga de eliminar todos los registros
   * de la entidad
  */
  public function deleteAll(){
    $em = $this->getEntityManager();
    return $em->createQuery('DELETE FROM UIFIIntegrantesBundle:IntegranteDirector')->execute();
  }

}
